import { StatusCodes } from 'http-status-codes';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { GrUpdate } from 'react-icons/gr';
import { MdLogout } from 'react-icons/md';
import Footer from '../components/Footer';
import TransactionsList from '../components/TransactionsList';
import TransferForm from '../components/TransferForm';
import service from '../service';
import styles from '../styles/pages/Dashboard.module.css';

export default function Dashboard() {
  const router = useRouter();
  const [token, setToken] = useState('');
  const [username, setUserName] = useState('');

  const [balance, setBalance] = useState('0,00');
  const [errorMessage, setErrorMessage] = useState('');

  const handleLogout = () => {
    localStorage.removeItem('userData');
    router.push('/');
  };

  const handleUpdateBalance = async (authorization: string) => {
    const response = await service.get.balance(authorization);
    const data = await response.json();

    switch (response.status) {
      case StatusCodes.OK:
        setErrorMessage('');
        setBalance(data.balance.toFixed(2).replace('.', ','));
        break;

      case StatusCodes.UNAUTHORIZED:
        handleLogout();
        break;

      default:
        setErrorMessage(data.message);
        break;
    }
  };

  useEffect(() => {
    const userData = localStorage.getItem('userData');

    if (!userData) {
      router.push('/');
    }

    const parsedData = JSON.parse(userData as string);

    setToken(parsedData.token);
    setUserName(parsedData.username);

    handleUpdateBalance(parsedData.token);
  }, []);

  return (
    <div className={styles.page}>
      <Head>
        <title>Bank - Início</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <span>LOGO</span>
        <div>
          <h1>{`Olá @${username}`}</h1>
          <button type="button" title="Logout" onClick={handleLogout}>
            <MdLogout />
          </button>
        </div>
      </header>

      <main>
        <section>
          <div>
            <button type="button" onClick={() => handleUpdateBalance(token)}>
              <GrUpdate />
            </button>
            <h2>Saldo disponível:</h2>
          </div>
          <span>{`R$ ${balance}`}</span>
          {!!errorMessage && <p>{errorMessage}</p>}
        </section>

        <TransferForm token={token} updateBalance={handleUpdateBalance} />

        <TransactionsList token={token} username={username} balance={balance} />
      </main>

      <Footer />
    </div>
  );
}
